//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTPortalOperation.h"

@interface DVTCreateProfileOperation : DVTPortalOperation
{
}

+ (id)operationWithSingleTeamToken:(id)arg1 profileName:(id)arg2 appId:(id)arg3 devices:(id)arg4 includeAllDevices:(BOOL)arg5 subPlatform:(id)arg6 andCertificates:(id)arg7;

@end

