//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class DVTDispatchLock, DVTNotificationToken, DVTSigningCertificateManager, NSArray, NSMapTable;

@interface DVTCertificateUtilities : NSObject
{
    DVTSigningCertificateManager *_signingCertificateManager;
    DVTNotificationToken *_changedNotificationToken;
    NSMapTable *_certificateRefToSigningCertificateMap;
    NSArray *_allSigningCertificates;
    NSArray *_allSigningCertificateObjects;
    DVTDispatchLock *_certificatesLock;
    NSMapTable *_hashToCertificateMap;
}

+ (id)sharedCertificateUtilities;
//- (void).cxx_destruct;
- (id)createCSRWithCommonName:(id)arg1 emailAddress:(id)arg2 privateKey:(struct OpaqueSecKeyRef **)arg3 andError:(id *)arg4;
- (_Bool)areCertificatesEqual:(struct OpaqueSecCertificateRef *)arg1 cert2:(struct OpaqueSecCertificateRef *)arg2;
- (id)expirationDateForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)issueDateForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)serialNumberForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)sha1HashForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)commonNameForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)defaultDesignatedRequirementsForIdentifier:(id)arg1 andCertificate:(struct OpaqueSecCertificateRef *)arg2;
- (_Bool)isCertificateTrusted:(struct OpaqueSecCertificateRef *)arg1;
- (id)certificateDataForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)signingCertificateWithData:(id)arg1;
- (_Bool)hasCertificateExpired:(struct OpaqueSecCertificateRef *)arg1;
- (_Bool)isCertificateAnIdentity:(struct OpaqueSecCertificateRef *)arg1;
- (id)portalMemberIDFromCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)portalTeamNameFromCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)portalTeamIDFromCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)trimmedNameForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)allSigningCertificateObjects;
- (id)allSigningCertificates;
- (id)allSigningCertificates_Sync;
- (_Bool)isCertificateKindAutomaticallyRevocable:(id)arg1;
- (_Bool)isCertificateKindRevocable:(id)arg1;
- (id)displayNameForCertificateKind:(id)arg1;
- (id)_certificateKindToCertificateKindNameMap;
- (id)certificateKindForCertificate:(struct OpaqueSecCertificateRef *)arg1;
- (id)likelyCertificateKindForCertificateDisplayName:(id)arg1;
- (id)signingCertificateForCertificateRef:(struct OpaqueSecCertificateRef *)arg1;
- (id)certificateRefToSigningCertificateMap;
- (void)backgroundSyncWithSigningCertificateManager;
- (id)signingCertificateManager;
- (id)init;

@end

