//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class DVTDiskStockManager, DVTFilePath;

@protocol DVTDiskStockMember <NSObject>
@property(readonly) NSString *diskStockMemberDisplayName;
@property(readonly) NSDate *diskStockMemberTTL;
@property(readonly) DVTFilePath *diskStockMemberRepresentation;
@property(readonly) __weak NSObject<DVTDiskStock> *diskStock;
- (long long)diskStockMemberCompareTo:(NSObject<DVTDiskStockMember> *)arg1;
- (void)diskStockManager:(DVTDiskStockManager *)arg1 didCullThisMemberFromDiskStock:(NSObject<DVTDiskStock> *)arg2;

@optional
- (BOOL)diskStockManager:(DVTDiskStockManager *)arg1 willCullThisMemberFromDiskStock:(NSObject<DVTDiskStock> *)arg2;
@end

