//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTDelayedInvocationScheduler.h"

@interface DVTDelayedInvocationDelayScheduler : DVTDelayedInvocationScheduler
{
    double _delay;
}

+ (id)schedulerWithDelay:(double)arg1;
@property(readonly, nonatomic) double delay; // @synthesize delay=_delay;
- (void)unscheduleDelayedInvocation:(id)arg1;
- (void)scheduleDelayedInvocation:(id)arg1;
- (id)initWithDelay:(double)arg1;

@end

