//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTDownloadProfileOperation.h"

@interface DVTDownloadTeamProfileOperation : DVTDownloadProfileOperation
{
}

+ (id)operationWithSingleTeamToken:(id)arg1 appIdIds:(id)arg2 andPlatform:(id)arg3 andSubPlatform:(id)arg4;
+ (id)operationWithSingleTeamToken:(id)arg1 appIdId:(id)arg2 andPlatform:(id)arg3 andSubPlatform:(id)arg4;
- (_Bool)_shouldRetryOnServiceError:(id)arg1;

@end

