//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "DVTDeveloperProfileAccountProvider-Protocol.h"

@class DVTDeveloperAccount, NSOrderedSet, NSString;

@interface DVTDeveloperAccountManager : NSObject <DVTDeveloperProfileAccountProvider>
{
    NSOrderedSet *_accounts;
    DVTDeveloperAccount *_defaultAccount;
}

+ (id)sharedAccountManager;
@property(retain, nonatomic) DVTDeveloperAccount *defaultAccount; // @synthesize defaultAccount=_defaultAccount;
//- (void).cxx_destruct;
@property(readonly) NSString *typeIdentifier;
- (BOOL)importAccountsFromKeychain:(struct OpaqueSecKeychainRef *)arg1 propertyList:(id)arg2 numberOfAccounts:(unsigned long long *)arg3 error:(id *)arg4;
- (BOOL)exportAccountsToKeychain:(struct OpaqueSecKeychainRef *)arg1 propertyList:(id *)arg2 numberOfAccounts:(unsigned long long *)arg3 error:(id *)arg4;
- (void)addAccountsFromArray:(id)arg1;
- (void)removeAccount:(id)arg1;
- (void)addAccount:(id)arg1;
@property(copy, nonatomic) NSOrderedSet *accounts; // @synthesize accounts=_accounts;
- (void)updateUserDefaults;
- (id)_accountsByCreatingFromDefaults;
- (id)_accountDefaultsWithFallbacks;
- (BOOL)hasAccountWithUsername:(id)arg1;
- (id)accountWithUsername:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

