//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class NSMutableDictionary;

@interface DVTDelayedInvocationNotificationHandler : NSObject
{
    NSMutableDictionary *_cacheKeyToSchedulersToDelayedInvocations;
    NSMutableDictionary *_cacheKeyToTokens;
}

+ (id)sharedInstance;
//- (void).cxx_destruct;
- (void)handleNotification:(id)arg1;
- (void)unregisterDelayedInvocation:(id)arg1 withScheduler:(id)arg2;
- (void)_unregisterAllObserversAndInvocationsForCacheKey:(id)arg1;
- (void)registerDelayedInvocation:(id)arg1 withScheduler:(id)arg2;
- (id)init;

@end

