//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "ITunesSoftwareServiceAuthenticationDelegate-Protocol.h"
#import "ITunesSoftwareServiceUploadDelegate-Protocol.h"

@class DVTLogAspect, NSString;

@interface DVTITunesConnectProxyDelegate : NSObject <ITunesSoftwareServiceUploadDelegate, ITunesSoftwareServiceAuthenticationDelegate>
{
    id <DVTDirectoryServicesSessionDescription> _session;
    DVTLogAspect *_logAspect;
    CDUnknownBlockType _willBeginCallback;
    CDUnknownBlockType _updatePercentageCallback;
    CDUnknownBlockType _updateMessageCallback;
    CDUnknownBlockType _shouldContinueCallback;
    CDUnknownBlockType _didCompleteCallback;
}

@property(copy) CDUnknownBlockType didCompleteCallback; // @synthesize didCompleteCallback=_didCompleteCallback;
@property(copy) CDUnknownBlockType shouldContinueCallback; // @synthesize shouldContinueCallback=_shouldContinueCallback;
@property(copy) CDUnknownBlockType updateMessageCallback; // @synthesize updateMessageCallback=_updateMessageCallback;
@property(copy) CDUnknownBlockType updatePercentageCallback; // @synthesize updatePercentageCallback=_updatePercentageCallback;
@property(copy) CDUnknownBlockType willBeginCallback; // @synthesize willBeginCallback=_willBeginCallback;
@property(retain, nonatomic) DVTLogAspect *logAspect; // @synthesize logAspect=_logAspect;
@property(retain, nonatomic) id <DVTDirectoryServicesSessionDescription> session; // @synthesize session=_session;
//- (void).cxx_destruct;
- (void)willAuthenticateWithContext:(id)arg1;
- (void)softwareService:(id)arg1 didCompleteUploadForApplication:(id)arg2;
- (BOOL)softwareService:(id)arg1 shouldContinueUploadForApplication:(id)arg2;
- (void)softwareService:(id)arg1 didUpdateStatusMessage:(id)arg2 forApplication:(id)arg3;
- (void)softwareService:(id)arg1 didUpdatePercentageComplete:(id)arg2 forApplication:(id)arg3;
- (void)softwareService:(id)arg1 willBeginUploadForApplication:(id)arg2;
- (id)initWithSession:(id)arg1 logAspect:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

