//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class DVTStackBacktrace;

@interface DVTMainThreadLatencyChecker_TimerTarget : NSObject
{
    DVTStackBacktrace *_creationBacktrace;
    id _realTarget;
    SEL _realSelector;
}

@property SEL realSelector; // @synthesize realSelector=_realSelector;
@property(retain) id realTarget; // @synthesize realTarget=_realTarget;
@property(retain) DVTStackBacktrace *creationBacktrace; // @synthesize creationBacktrace=_creationBacktrace;
//- (void).cxx_destruct;
- (void)timerFireMethod:(id)arg1;

@end

