//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "DVTCodesignableDevice-Protocol.h"

@class DVTPlatform, NSMutableSet, NSSet, NSString;

@interface DVTMockCodesignableDevice : NSObject <DVTCodesignableDevice>
{
    BOOL _supportsProvisioningMock;
    NSString *_nameMock;
    NSString *_nameForDeveloperPortalMock;
    NSString *_identifierMock;
    NSString *_platformIdentifierMock;
    NSMutableSet *_proxiedDevicesMock;
}

@property(retain) NSMutableSet *proxiedDevicesMock; // @synthesize proxiedDevicesMock=_proxiedDevicesMock;
@property BOOL supportsProvisioningMock; // @synthesize supportsProvisioningMock=_supportsProvisioningMock;
@property(copy) NSString *platformIdentifierMock; // @synthesize platformIdentifierMock=_platformIdentifierMock;
@property(copy) NSString *identifierMock; // @synthesize identifierMock=_identifierMock;
@property(copy) NSString *nameForDeveloperPortalMock; // @synthesize nameForDeveloperPortalMock=_nameForDeveloperPortalMock;
@property(copy) NSString *nameMock; // @synthesize nameMock=_nameMock;
//- (void).cxx_destruct;
@property(readonly) DVTPlatform *platform;
@property(readonly, copy) NSSet *proxiedDevices;
@property(readonly) BOOL supportsProvisioning;
@property(readonly, copy) NSString *platformIdentifier;
@property(readonly, copy, nonatomic) NSString *identifier;
@property(readonly, copy) NSString *nameForDeveloperPortal;
@property(readonly, copy, nonatomic) NSString *name;
- (id)snapshot;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPlist:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

