//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class DVTFilePath;

@interface DVTProvisioningTemporaryStateManager : NSObject
{
    struct OpaqueSecKeychainRef *_keychain;
    DVTFilePath *_provisioningProfileSearchPath;
}

+ (id)provisioningProfileSearchPath;
+ (id)defaultTemporaryStateManager;
@property(retain) DVTFilePath *provisioningProfileSearchPath; // @synthesize provisioningProfileSearchPath=_provisioningProfileSearchPath;
@property struct OpaqueSecKeychainRef *keychain; // @synthesize keychain=_keychain;
//- (void).cxx_destruct;
- (id)initWithKeychain:(struct OpaqueSecKeychainRef *)arg1 provisioningProfileSearchPath:(id)arg2;

@end

