//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class NSString;

@interface DVTStackBacktraceFrame : NSObject
{
    unsigned long long _stackAddress;
    unsigned long long _lineNumber;
    NSString *_symbolName;
    NSString *_fileName;
    NSString *_symbolOwnerName;
    NSString *_rawSymbolName;
}

@property(copy) NSString *rawSymbolName; // @synthesize rawSymbolName=_rawSymbolName;
@property(copy) NSString *symbolOwnerName; // @synthesize symbolOwnerName=_symbolOwnerName;
@property(copy) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy) NSString *symbolName; // @synthesize symbolName=_symbolName;
@property unsigned long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property unsigned long long stackAddress; // @synthesize stackAddress=_stackAddress;
//- (void).cxx_destruct;
- (id)frameStringRepresentationWithAddress:(BOOL)arg1;
- (id)frameStringRepresentation;
- (id)_initWithStackAddress:(unsigned long long)arg1 usingSymbolicator:(struct _CSTypeRef)arg2;

@end

