//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "DVTStreamingZipArchiver-Protocol.h"

@class NSString;

@interface DVTStreamingZip : NSObject <DVTStreamingZipArchiver>
{
}

+ (id)sharedInstance;
- (_Bool)extractStreamableZipAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (_Bool)createStreamableZipOfDirectory:(id)arg1 atPath:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (_Bool)createStreamableZipOfDirectory:(id)arg1 atPath:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

