//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "DVTUserDefaults-Protocol.h"

@class NSMutableDictionary, NSString;

@interface DVTUserDefaultsStub : NSObject <DVTUserDefaults>
{
    NSMutableDictionary *_storage;
}

//- (void).cxx_destruct;
- (id)URLForKey:(id)arg1;
- (double)doubleForKey:(id)arg1;
- (id)stringArrayForKey:(id)arg1;
- (long long)integerForKey:(id)arg1;
- (float)floatForKey:(id)arg1;
- (id)dataForKey:(id)arg1;
- (id)dictionaryForKey:(id)arg1;
- (id)arrayForKey:(id)arg1;
- (BOOL)boolForKey:(id)arg1;
- (id)stringForKey:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

