//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@interface NSManagedObjectContext (DVTNSManagedObjectContextAdditions)
- (void)dvt_disallowOperationFinish:(id)arg1 whilePerformingBlock:(CDUnknownBlockType)arg2;
- (void)dvt_disallowOperationFinish:(id)arg1 withReason:(id)arg2 whilePerformingBlock:(CDUnknownBlockType)arg3;
@end

