//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@interface NSObject (DVTInvalidation_Private)
+ (void)_dvt_synthesizeInvalidationWithDeallocAssertion:(BOOL)arg1 multipleInvalidationAssertion:(BOOL)arg2;
+ (void)_dvt_synthesizeInvalidationWithoutDeallocAssertion;
+ (id)_dvt_invalidatableClasses;
@end

