//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@interface NSPointerArray (DVTNSPointerArrayAdditions)
- (unsigned long long)dvt_indexOfObjectIdenticalTo:(id)arg1;
- (void)dvt_replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)dvt_insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)dvt_objectAtIndex:(unsigned long long)arg1;
- (void)dvt_addObject:(id)arg1;
@end

