//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@interface NSXMLElement (DVTFoundationClassAdditions)
+ (id)dvt_elementWithXMLStringByPreservingWhitespace:(id)arg1 error:(id *)arg2;
- (BOOL)dvt_isApplicableForCurrentRuntimeOSVersion;
- (id)dvt_elementsApplicableForCurrentRuntimeOSVersionForName:(id)arg1;
- (id)dvt_elementsApplicableForCurrentRuntimeOSVersion;
@end

