//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DTXMessenger.h"

@class DTXConnection, NSObject<OS_dispatch_queue>, NSString;

@interface DTXChannel : NSObject <DTXMessenger>
{
    NSString *_label;
    DTXConnection *_connection;
    DTXConnection *_strongConnection;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSObject<OS_dispatch_queue> *_atomicHandlers;
    id <DTXAllowedRPC> _dispatchTarget;
    CDUnknownBlockType _messageHandler;
    CDUnknownBlockType _dispatchValidator;
    BOOL _canceled;
    unsigned int _channelCode;
    int _compressionTypeHint;
}

@property int compressionTypeHint; // @synthesize compressionTypeHint=_compressionTypeHint;
@property(readonly, nonatomic) unsigned int channelCode; // @synthesize channelCode=_channelCode;
@property BOOL isCanceled; // @synthesize isCanceled=_canceled;
- (void).cxx_destruct;
- (void)sendMessageSync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)sendMessage:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (BOOL)sendMessageAsync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)sendControlSync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)sendControlAsync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)_setTargetQueue:(id)arg1;
- (void)resume;
- (void)suspend;
- (void)cancel;
- (void)registerDisconnectHandler:(CDUnknownBlockType)arg1;
- (void)_setDispatchValidator:(CDUnknownBlockType)arg1;
@property(retain) id <DTXAllowedRPC> dispatchTarget;
@property(copy, nonatomic) CDUnknownBlockType messageHandler;
@property(copy, nonatomic) NSString *label;
- (void)_scheduleMessage:(id)arg1 tracker:(id)arg2 withHandler:(CDUnknownBlockType)arg3;
- (void)_scheduleBlock:(CDUnknownBlockType)arg1;
- (id)initWithConnection:(id)arg1 channelIdentifier:(unsigned int)arg2 label:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

