//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "SimDisplayDescriptorState-Protocol.h"

@interface DefaultDisplayDescriptorState : NSObject <SimDisplayDescriptorState>
{
    int _powerState;
    int _displayClass;
    unsigned int _defaultWidthForDisplay;
    unsigned int _defaultHeightForDisplay;
}

+ (id)defaultDisplayDescriptorStateWithPowerState:(int)arg1 displayClass:(int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4;
@property(nonatomic) unsigned int defaultHeightForDisplay; // @synthesize defaultHeightForDisplay=_defaultHeightForDisplay;
@property(nonatomic) unsigned int defaultWidthForDisplay; // @synthesize defaultWidthForDisplay=_defaultWidthForDisplay;
@property(nonatomic) int displayClass; // @synthesize displayClass=_displayClass;
@property(nonatomic) int powerState; // @synthesize powerState=_powerState;
- (id)xpcObject;

@end

