//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@protocol SimDeviceIOLogger <NSObject>
- (void)deviceIOLogError:(NSError *)arg1 message:(NSString *)arg2;
- (void)deviceIOLogLevel:(int)arg1 message:(NSString *)arg2;
@end

