//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimDeviceIOLogger.h"

@class NSString;

@interface SimDeviceIOServerLogger : NSObject <SimDeviceIOLogger>
{
    NSString *_bundleIdentifier;
}

@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;
- (void)deviceIOLogError:(id)arg1 message:(id)arg2;
- (void)deviceIOLogLevel:(int)arg1 message:(id)arg2;
- (id)initForBundleIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

