//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSDictionary, NSString;

@interface SimDeviceBootInfo : NSObject <NSSecureCoding>
{
    BOOL _isTerminalStatus;
    unsigned int _status;
    double _bootElapsedTime;
    NSDictionary *_info;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSDictionary *info; // @synthesize info=_info;
@property(nonatomic) BOOL isTerminalStatus; // @synthesize isTerminalStatus=_isTerminalStatus;
@property(nonatomic) double bootElapsedTime; // @synthesize bootElapsedTime=_bootElapsedTime;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
- (void).cxx_destruct;
@property(readonly, nonatomic) double migrationElapsedTime;
@property(readonly, nonatomic) NSString *migrationPhaseDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithElapsedTime:(double)arg1 status:(unsigned int)arg2 info:(id)arg3;

@end

