//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;


@class NSArray<SimDeviceIOPortInterface>, NSObject, NSObject, NSUUID;

@protocol SimDeviceIOProtocol <NSObject>
- (void)detachConsumer:(NSObject *)arg1 fromPort:(NSObject *)arg2;
- (void)attachConsumer:(NSObject *)arg1 toPort:(NSObject *)arg2;
- (NSArray *)ioPorts;
- (NSObject *)ioPortForUUID:(NSUUID *)arg1;
@end

