//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;
@protocol SimDeviceIOBundleInterface;
@class NSBundle;

@interface SimDeviceIOLoadedBundle : NSObject
{
    NSBundle *_bundle;
    id <SimDeviceIOBundleInterface> _bundleInterface;
}

+ (id)loadedBundleForURL:(id)arg1;
@property(retain, nonatomic) id <SimDeviceIOBundleInterface> bundleInterface; // @synthesize bundleInterface=_bundleInterface;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
//- (void).cxx_destruct;
- (id)initWithURL:(id)arg1;

@end

