//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SimDeviceIO.h"

@class NSArray, NSMutableDictionary, NSObject;

@interface SimDeviceIOClient : SimDeviceIO
{
    NSArray *_deviceIOPorts;
    struct NSMutableDictionary *_consumerProxies;
    NSObject<OS_dispatch_queue> *_executionQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *executionQueue; // @synthesize executionQueue=_executionQueue;
@property(retain, nonatomic) NSMutableDictionary *consumerProxies; // @synthesize consumerProxies=_consumerProxies;
@property(retain, nonatomic) NSArray *deviceIOPorts; // @synthesize deviceIOPorts=_deviceIOPorts;
//- (void).cxx_destruct;
- (void)updateIOPorts;
- (void)detachConsumer:(id)arg1 fromPort:(id)arg2;
- (void)attachConsumer:(id)arg1 toPort:(id)arg2;
- (id)ioPorts;
- (id)initWithDevice:(id)arg1;

@end

