//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "NSPasteboardItemDataProvider-Protocol.h"
@class NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSPasteboardItem, NSString;

@interface SimPasteboardItem : NSObject <NSPasteboardItemDataProvider>
{
    BOOL _typesAllResolved;
    NSMutableDictionary *_dataDictionary;
    NSMutableArray *_preferredOrderedTypes;
    NSMapTable *_promisedDataTypes;
    NSPasteboardItem *_nsPasteboardItem;
}

+ (id)itemFromNSPasteboardItem:(id)arg1 options:(id)arg2;
@property(nonatomic) BOOL typesAllResolved; // @synthesize typesAllResolved=_typesAllResolved;
@property(retain, nonatomic) NSPasteboardItem *nsPasteboardItem; // @synthesize nsPasteboardItem=_nsPasteboardItem;
@property(retain, nonatomic) NSMapTable *promisedDataTypes; // @synthesize promisedDataTypes=_promisedDataTypes;
@property(retain, nonatomic) NSMutableArray *preferredOrderedTypes; // @synthesize preferredOrderedTypes=_preferredOrderedTypes;
@property(retain, nonatomic) NSMutableDictionary *dataDictionary; // @synthesize dataDictionary=_dataDictionary;
//- (void).cxx_destruct;
- (void)resolveAllTypes;
- (void)pasteboard:(id)arg1 item:(id)arg2 provideDataForType:(id)arg3;
@property(readonly, copy, nonatomic) NSPasteboardItem *nsPasteboardRepresentation;
@property(readonly, copy, nonatomic) NSArray *types;
- (id)valueForType:(id)arg1;
- (BOOL)setValue:(id)arg1 forType:(id)arg2;
- (BOOL)setDataProvider:(id)arg1 forTypes:(id)arg2;
@property(readonly, copy) NSString *description;
- (id)init;
@property(readonly, copy, nonatomic) NSArray *internalRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wincompatible-property-type"
@property(readonly) unsigned long long hash;
#pragma clang diagnostic pop
@property(readonly) Class superclass;

@end

