//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class NSArray, NSMutableDictionary, NSObject;

@interface SimPasteboardPortMap : NSObject
{
    NSArray *_pasteboardItems;
    NSMutableDictionary *_portToProxyMap;
    NSObject *_concurrentQueue;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSObject *concurrentQueue; // @synthesize concurrentQueue=_concurrentQueue;
@property(retain, nonatomic) NSMutableDictionary *portToProxyMap; // @synthesize portToProxyMap=_portToProxyMap;
@property(retain, nonatomic) NSArray *pasteboardItems; // @synthesize pasteboardItems=_pasteboardItems;
//- (void).cxx_destruct;
- (id)createPortKey:(unsigned int)arg1;
- (void)setValue:(id)arg1 forPort:(unsigned int)arg2;
- (id)lookupWith:(unsigned int)arg1;
- (id)description;
- (id)init;

@end

