//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimAudioDescriptorState.h"

@class NSString;

@interface SimAudioHostRouteDescriptorState : NSObject <SimAudioDescriptorState>
{
    int _powerState;
    NSString *_guestDataPath;
}

+ (id)defaultAudioDescriptorStateWithPowerState:(int)arg1 guestDataPath:(id)arg2;
@property(copy, nonatomic) NSString *guestDataPath; // @synthesize guestDataPath=_guestDataPath;
@property(nonatomic) int powerState; // @synthesize powerState=_powerState;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

