//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimDisplayDescriptorState.h"

@class NSString, NSURL;

@interface SimDisplayDefaultDescriptorState : NSObject <SimDisplayDescriptorState>
{
    unsigned short _displayClass;
    int _powerState;
    unsigned int _defaultWidthForDisplay;
    unsigned int _defaultHeightForDisplay;
    unsigned int _defaultPixelFormat;
    NSURL *_mask;
}

+ (id)defaultDisplayDescriptorStateWithPowerState:(int)arg1 displayClass:(unsigned short)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 pixelFormat:(unsigned int)arg5 mask:(id)arg6;
@property(retain, nonatomic) NSURL *mask; // @synthesize mask=_mask;
@property(nonatomic) unsigned int defaultPixelFormat; // @synthesize defaultPixelFormat=_defaultPixelFormat;
@property(nonatomic) unsigned int defaultHeightForDisplay; // @synthesize defaultHeightForDisplay=_defaultHeightForDisplay;
@property(nonatomic) unsigned int defaultWidthForDisplay; // @synthesize defaultWidthForDisplay=_defaultWidthForDisplay;
@property(nonatomic) unsigned short displayClass; // @synthesize displayClass=_displayClass;
@property(nonatomic) int powerState; // @synthesize powerState=_powerState;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

