//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;
#import "NSSecureCoding-Protocol.h"

@class NSData;

@interface SimPasteboardItemWrappedData : NSObject <NSSecureCoding>
{
    NSData *_wrappedData;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSData *wrappedData; // @synthesize wrappedData=_wrappedData;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithData:(id)arg1;

@end

