//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SimPasteboardSyncPoolObject : NSObject
{
    unsigned long long _lastSeenChangeCount;
    unsigned long long _regID;
}

@property(nonatomic) unsigned long long regID; // @synthesize regID=_regID;
@property(nonatomic) unsigned long long lastSeenChangeCount; // @synthesize lastSeenChangeCount=_lastSeenChangeCount;
- (id)initWithPasteboard:(id)arg1;

@end

