//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class NSArray;

@interface SimRuntimePairingReuirements : NSObject
{
    unsigned int _minOSVersion;
    NSArray *_supportedProductFamilies;
    unsigned long long _maxPairs;
}

@property(nonatomic) unsigned long long maxPairs; // @synthesize maxPairs=_maxPairs;
@property(copy, nonatomic) NSArray *supportedProductFamilies; // @synthesize supportedProductFamilies=_supportedProductFamilies;
@property(nonatomic) unsigned int minOSVersion; // @synthesize minOSVersion=_minOSVersion;

@end

