//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, _XCTContextImplementation;

@interface XCTContext : NSObject
{
    id _internalImplementation;
}

+ (void)popCurrentContextInThread:(id)arg1;
+ (_Bool)hasContextInThread:(id)arg1;
+ (id)currentContextInThread:(id)arg1;
+ (id)_currentContextInThread:(id)arg1;
+ (void)pushCurrentContext:(id)arg1 inThread:(id)arg2;
+ (void)runInContextForTestCase:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (_Bool)shouldReportActivityWithType:(id)arg1 inTestMode:(long long)arg2;
+ (_Bool)_shouldReportActivityWithType:(id)arg1;
+ (void)_runActivityNamed:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)runActivityNamed:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)currentContext;
@property(retain) _XCTContextImplementation *internalImplementation; // @synthesize internalImplementation=_internalImplementation;
@property(readonly) NSDictionary *aggregationRecords;
- (id)topActivity;
- (long long)activityRecordStackDepth;
- (void)unwindRemainingActivities;
- (void)_runActivityNamed:(id)arg1 type:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)didFinishActivity:(id)arg1;
- (id)willStartActivityWithTitle:(id)arg1 type:(id)arg2;
- (id)initInternally;
- (void)_runActivityNamed:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)dealloc;

@end

