//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCTRunnerAutomationSession.h"

@class NSString, NSXPCConnection;

@interface XCTRunnerAutomationSession : NSObject <XCTRunnerAutomationSession>
{
    NSXPCConnection *_connection;
}

@property NSXPCConnection *connection; // @synthesize connection=_connection;
- (id)matchesForQuery:(id)arg1 error:(id *)arg2;
- (id)initWithEndpoint:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

