//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XCTUniformTypeIdentifier : NSObject
{
}

+ (_Bool)isImageUTI:(id)arg1;
+ (id)inferredUTIForFileExtension:(id)arg1;
+ (id)zipArchive;
+ (id)XMLPropertyList;
+ (id)GIF;
+ (id)TIFF;
+ (id)JPEG;
+ (id)PNG;
+ (id)plainText;
+ (id)data;

@end

