//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTAutomationSupport/XCTAccessibilityFramework-Protocol.h>

@class NSString;

@interface XCTAccessibilityFramework : NSObject <XCTAccessibilityFramework>
{
    _Bool _allowsRemoteAccess;
    int _processID;
    struct __AXUIElement *_systemWideElement;
}

@property struct __AXUIElement *systemWideElement; // @synthesize systemWideElement=_systemWideElement;
@property(readonly) int processID; // @synthesize processID=_processID;
@property(readonly) _Bool allowsRemoteAccess; // @synthesize allowsRemoteAccess=_allowsRemoteAccess;
- (void)performWithAXTimeout:(double)arg1 block:(CDUnknownBlockType)arg2;
- (id)attributes:(id)arg1 forElement:(struct __AXUIElement *)arg2 error:(id *)arg3;
- (long long)appOrientationForElement:(struct __AXUIElement *)arg1 error:(id *)arg2;
- (struct CGRect)frameForElement:(struct __AXUIElement *)arg1 error:(id *)arg2;
- (const struct __AXUIElement *)mainWindowForElement:(struct __AXUIElement *)arg1 error:(id *)arg2;
- (id)userTestingSnapshotForElement:(struct __AXUIElement *)arg1 options:(id)arg2 error:(id *)arg3;
- (void)_setAXRequestingClient;
- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (_Bool)_canAccessElement:(struct __AXUIElement *)arg1 withError:(id *)arg2;
- (void)dealloc;
- (id)initForLocalAccess;
- (id)initForRemoteAccess;
- (id)initAllowingRemoteAccess:(_Bool)arg1 processID:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

