//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTAutomationSupport/NSCopying-Protocol.h>
#import <XCTAutomationSupport/NSSecureCoding-Protocol.h>

@class NSData, UIImage, XCTImageEncoding, XCTImageMetadata;

@interface XCTImage : NSObject <NSCopying, NSSecureCoding>
{
    XCTImageMetadata *_metadata;
    NSData *_data;
    XCTImageEncoding *_encoding;
    UIImage *_platformImage;
}

+ (_Bool)supportsSecureCoding;
+ (id)emptyImageWithSize:(struct CGSize)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *platformImage; // @synthesize platformImage=_platformImage;
@property(readonly, copy, nonatomic) XCTImageEncoding *encoding; // @synthesize encoding=_encoding;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
@property(readonly, nonatomic) XCTImageMetadata *metadata; // @synthesize metadata=_metadata;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)debugQuickLookObject;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCGImage:(struct CGImage *)arg1 metadata:(id)arg2 orientation:(unsigned int)arg3;
- (id)initWithData:(id)arg1 encodedIn:(id)arg2 metadata:(id)arg3;
- (id)initWithImage:(id)arg1;

@end

