//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface XCTImageConverter : NSObject
{
}

+ (id)_dataForImage:(id)arg1 encoding:(id)arg2 metadata:(id)arg3;
+ (id)dataFromImage:(id)arg1 enforceEncoding:(id)arg2;
+ (id)convertImageIfNecessary:(id)arg1 usingPreferredEncoding:(id)arg2;

@end

