//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTAutomationSupport/NSObject-Protocol.h>

@class NSDate, NSString;

@protocol XCTLogArchiveRequesting <NSObject>
+ (id)requestWithStartDate:(NSDate *)arg1 outputPath:(NSString *)arg2;
@property(readonly, copy) NSString *outputPath;
@property(readonly, copy) NSDate *startDate;
- (void)executeWithCompletion:(void (^)(_Bool, NSError *))arg1;
@end

