//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface XCTMainRunLoopIdleNotifier : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_idleHandlers;
    struct __CFRunLoopObserver *_runLoopObserver;
}

- (void).cxx_destruct;
@property struct __CFRunLoopObserver *runLoopObserver; // @synthesize runLoopObserver=_runLoopObserver;
@property(readonly) NSMutableArray *idleHandlers; // @synthesize idleHandlers=_idleHandlers;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)handleIdleObserved;
- (void)_queue_setUpRunLoopObserver;
- (void)notifyWhenIdle:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

