//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTAutomationSupport/NSObject-Protocol.h>

@class NSSet, XCElementSnapshot;
@protocol XCTElementSetTransformer;

@protocol XCTMatchingElementIterator <NSObject>
@property(readonly) id <XCTElementSetTransformer> transformer;
@property(readonly) NSSet *currentRelatedElements;
@property(readonly) XCElementSnapshot *currentMatch;
- (XCElementSnapshot *)nextMatch;
@end

