//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTAutomationSupport/NSObject-Protocol.h>

@class XCTRuntimeIssueContext;
@protocol XCTRuntimeIssue;

@protocol XCTRuntimeIssueContextReportingDelegate <NSObject>
+ (_Bool)shouldRuntimeIssueContext:(XCTRuntimeIssueContext *)arg1 reportIssue:(id <XCTRuntimeIssue>)arg2;
@end

