//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTAutomationSupport/NSSecureCoding-Protocol.h>

@class NSString;

@interface XCTSpindumpRequestSpecification : NSObject <NSSecureCoding>
{
    int _processID;
    unsigned long long _durationMilliseconds;
    unsigned long long _intervalMicroseconds;
    unsigned long long _spindumpFlags;
    NSString *_reason;
    NSString *_signature;
    NSString *_filename;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly) NSString *filename; // @synthesize filename=_filename;
@property(readonly) NSString *signature; // @synthesize signature=_signature;
@property(readonly) NSString *reason; // @synthesize reason=_reason;
@property(readonly) unsigned long long spindumpFlags; // @synthesize spindumpFlags=_spindumpFlags;
@property(readonly) unsigned long long intervalMicroseconds; // @synthesize intervalMicroseconds=_intervalMicroseconds;
@property(readonly) unsigned long long durationMilliseconds; // @synthesize durationMilliseconds=_durationMilliseconds;
@property(readonly) int processID; // @synthesize processID=_processID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)init;
- (id)initWithProcessID:(int)arg1;
- (id)initWithProcessID:(int)arg1 durationMilliseconds:(unsigned long long)arg2 intervalMicroseconds:(unsigned long long)arg3 spindumpFlags:(unsigned long long)arg4 reason:(id)arg5 signature:(id)arg6 filename:(id)arg7;

@end

