//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTAutomationSupport/NSSecureCoding-Protocol.h>

@class XCTImageEncoding;

@interface XCTScreenshotRequest : NSObject <NSSecureCoding>
{
    unsigned int _screenID;
    XCTImageEncoding *_encoding;
    struct CGRect _rect;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly) XCTImageEncoding *encoding; // @synthesize encoding=_encoding;
@property(readonly) struct CGRect rect; // @synthesize rect=_rect;
@property(readonly) unsigned int screenID; // @synthesize screenID=_screenID;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithScreenID:(unsigned int)arg1 rect:(struct CGRect)arg2 encoding:(id)arg3;

@end

