//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTAutomationSupport/NSSecureCoding-Protocol.h>

@interface XCTTimeoutControls : NSObject <NSSecureCoding>
{
    double _mainThreadResponsivenessTimeout;
    double _queryExecutionTimeout;
}

+ (_Bool)supportsSecureCoding;
+ (id)standardTimeoutControls;
+ (double)defaultQueryExecutionTimeout;
+ (void)setDefaultQueryExecutionTimeout:(double)arg1;
+ (double)defaultMainThreadResponsivenessTimeout;
+ (void)setDefaultMainThreadResponsivenessTimeout:(double)arg1;
@property double queryExecutionTimeout; // @synthesize queryExecutionTimeout=_queryExecutionTimeout;
@property double mainThreadResponsivenessTimeout; // @synthesize mainThreadResponsivenessTimeout=_mainThreadResponsivenessTimeout;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

