//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@interface SimDeviceFramebufferBackingStore : NSObject
{
    unsigned int _port;
    unsigned long long _pixelsWide;
    unsigned long long _pixelsHigh;
    unsigned long long _rowByteSize;
    unsigned long long _size;
    struct __IOSurface *_ioSurface;
    NSObject *_imageDataAccessQueue;
    void *_data;
}

+ (id)allocateNewBackingStoreWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 error:(id *)arg3;
@property(nonatomic) void *data; // @synthesize data=_data;
@property(nonatomic) unsigned int port; // @synthesize port=_port;
@property(retain, nonatomic) NSObject *imageDataAccessQueue; // @synthesize imageDataAccessQueue=_imageDataAccessQueue;
@property(nonatomic) struct __IOSurface *ioSurface; // @synthesize ioSurface=_ioSurface;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) unsigned long long rowByteSize; // @synthesize rowByteSize=_rowByteSize;
@property(nonatomic) unsigned long long pixelsHigh; // @synthesize pixelsHigh=_pixelsHigh;
@property(nonatomic) unsigned long long pixelsWide; // @synthesize pixelsWide=_pixelsWide;
//- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGImage *image;
- (void)flushDamageRegion:(struct CGRect)arg1;
- (void)flushEntireLiveBuffer;
- (void)accessBackingStoreDuring:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)invalidate;
- (id)initWithData:(void *)arg1 port:(unsigned int)arg2 size:(unsigned long long)arg3 rowByteSize:(unsigned long long)arg4 pixelsWide:(unsigned long long)arg5 pixelsHigh:(unsigned long long)arg6;

@end

