//  Copyright 2016 LinkedIn Corporation
//  Licensed under the BSD 2-Clause License (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://opensource.org/licenses/BSD-2-Clause
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OF ANY KIND, either express or implied.  See the License for the specific language governing permissions and limitations under the License.

#ifndef BPTestReportHTML_h
#define BPTestReportHTML_h

// Leaving this html content as source instead of resouce since Bluepill is a CLI tool with no resource bundles
static const NSString * const kHTMLContent = @"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <meta charset=\"utf-8\">\n"
"        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
"        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"        <title>Test Report</title>\n"
"        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\n"
"        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n"
"        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n"
"        <!--[if lt IE 9]>\n"
"        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n"
"        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n"
"        <![endif]-->\n"
"        <style>\n"
"            .display-none {\n"
"                display: none;\n"
"            }\n"
"\n"
"            .table {\n"
"                table-layout: fixed;\n"
"            }\n"
"\n"
"            td.test-name {\n"
"                word-wrap: break-word;\n"
"                max-width: 800px;\n"
"            }\n"
"\n"
"            td.test-error {\n"
"                white-space: pre-line;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"\n"
"    <body>\n"
"        <script src=\"https://code.jquery.com/jquery-1.11.3.min.js\" type=\"text/javascript\"></script>\n"
"        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\n"
"        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.2/handlebars.min.js\" type=\"text/javascript\"></script>\n"
"        <script src=\"test-report.js\" type=\"text/javascript\"></script>\n"
"\n"
"        <script id=\"body-template\" type=\"text/x-handlebars-template\">\n"
"            <nav class=\"navbar navbar-default navbar-static-top\">\n"
"                <div class=\"container\">\n"
"                    <div class=\"navbar-header\">\n"
"                        <a class=\"navbar-brand\" href=\"#\">{{product}}</a>\n"
"                    </div>\n"
"                    <div id=\"navbar\" class=\"navbar-collapse collapse\">\n"
"                        <ul class=\"nav navbar-nav\">\n"
"                            <li>\n"
"                                <p class=\"navbar-text\">\n"
"                                    <span class=\"label label-default {{#if failed}}label-danger{{else}}label-success{{/if}}\">{{#if failed}}Failed{{else}}Succeeded{{/if}}</span>\n"
"                                </p>\n"
"                            </li>\n"
"                        </ul>\n"
"                    </div>\n"
"                </div>\n"
"            </nav>\n"
"\n"
"            <div class=\"container\">\n"
"                <div class=\"test-suites-container\">\n"
"                    <table class=\"table table-bordered\" style=\"width: auto !important\">\n"
"                        <thead>\n"
"                            <th>Test Suite Name</th>\n"
"                            <th>Total Tests</th>\n"
"                            <th>Total Time</th>\n"
"                            <th>Passed on first try</th>\n"
"                            <th>Passed on retry</th>\n"
"                            <th>Failed</th>\n"
"                            <th>Details</th>\n"
"                        </thead>\n"
"                        <tbody>\n"
"                        {{#each testSuites}}\n"
"                            {{> testSuiteTableRowTemplate}}\n"
"                        {{/each}}\n"
"                        </tbody>\n"
"                    </table>\n"
"                </div>\n"
"\n"
"                {{#each testSuites}}\n"
"                <div class=\"test-suite-details-container\">\n"
"                    <a href=\"#\" class=\"test-suite-link\" data-index=\"{{@index}}\"><h4>{{name}}</h4></a>\n"
"                    <table class=\"table table-bordered display-none test-suite-details-table-{{@index}}\" style=\"width: auto !important\">\n"
"                        <thead>\n"
"                            <th>Test</th>\n"
"                            <th>Status</th>\n"
"                            <th>Time</th>\n"
"                            <th>Details</th>\n"
"                        </thead>\n"
"                        <tbody>\n"
"                        {{#each testCases}}\n"
"                            {{> testSuiteDetailsTableRowTemplate}}\n"
"                        {{/each}}\n"
"                        </tbody>\n"
"                    </table>\n"
"                </div>\n"
"                {{/each}}\n"
"            </div>\n"
"        </script>\n"
"\n"
"        <script id=\"test-suite-table-row-template\" type=\"text/x-handlebars-template\">\n"
"            <tr class=\"{{#if failed}}danger{{else}}success{{/if}}\">\n"
"                <td>{{name}}</td>\n"
"                <td>{{numTotalTests}}</td>\n"
"                <td>{{time}}</td>\n"
"                <td>{{numPassedOnFirstTry}}</td>\n"
"                <td class=\"info\">{{numPassedOnRetry}}</td>\n"
"                <td class=\"danger\">{{numFinalFailed}}</td>\n"
"                <td><a href=\"#\" class=\"btn btn-xs {{#if failed}}btn-danger{{else}}btn-success{{/if}} test-suite-link\" data-index=\"{{@index}}\">Details</a></td>\n"
"            </tr>\n"
"        </script>\n"
"\n"
"        <script id=\"test-suite-details-row-template\" type=\"test/x-handlebars-template\">\n"
"            <tr class=\"{{#if failedFinal}}danger{{else}}{{#if passedOnRetry}}{{#if failed}}warning{{else}}info{{/if}}{{else}}success{{/if}}{{/if}}\">\n"
"                <td class=\"test-name\">{{className}}#{{name}}</td>\n"
"                <td>{{#if failed}}Failed{{else}}Passed{{/if}}</td>\n"
"                <td>{{time}}</td>\n"
"                <td>\n"
"                    {{#if errors.length}}<a href=\"#\" class=\"btn btn-xs btn-primary test-suite-details-row-details-button\" data-index=\"{{@index}}\">Errors</a>{{/if}}\n"
"                    {{#if artifacts.length}}<a href=\"#\" class=\"btn btn-xs btn-primary test-suite-details-row-artifacts-button\" data-index=\"{{@index}}\">Artifacts</a>{{/if}}\n"
"                </td>\n"
"            </tr>\n"
"            {{#if errors.length}}\n"
"            <tr class=\"display-none test-suite-details-error-row test-suite-details-error-row-{{@index}}\">\n"
"                <td class=\"test-error\" colspan=6>\n"
"                    {{#each errors}}\n"
"                    <p>{{message}}</p>\n"
"                    <p><i>{{location}}</i></p>\n"
"                    {{/each}}\n"
"                </td>\n"
"            </tr>\n"
"            {{/if}}\n"
"            {{#if artifacts.length}}\n"
"            <tr class=\"display-none test-suite-details-artifacts-row test-suite-details-artifacts-row-{{@index}}\">\n"
"                <td colspan=6>\n"
"                    {{#each artifacts}}\n"
"                    <p><a href=\"{{filePath}}\" target=\"_blank\">{{filePath}}</a></p>\n"
"                    {{/each}}\n"
"                </td>\n"
"            </tr>\n"
"            {{/if}}\n"
"        </script>\n"
"\n"
"        <script type=\"text/javascript\">\n"
"            var templates = {}\n"
"            templates.testSuiteTableRowTemplate = Handlebars.compile($('#test-suite-table-row-template').html());\n"
"            templates.testSuiteDetailsTableRowTemplate = Handlebars.compile($('#test-suite-details-row-template').html());\n"
"            templates.bodyTemplate = Handlebars.compile($('#body-template').html());\n"
"\n"
"            Handlebars.registerPartial(\"testSuiteTableRowTemplate\", templates.testSuiteTableRowTemplate);\n"
"            Handlebars.registerPartial(\"testSuiteDetailsTableRowTemplate\", templates.testSuiteDetailsTableRowTemplate);\n"
"        </script>\n"
"\n"
"        <script type=\"text/javascript\">\n"
"            var TestReport = function(json) {\n"
"                this.product = json.product;\n"
"                this.failed = json.failed;\n"
"                this.timestamp = json.timestamp;\n"
"\n"
"                var testSuites = [];\n"
"                $.each(json.testSuites, function(index, testSuite) {\n"
"                    testSuites.push(new TestSuite(testSuite))\n"
"                });\n"
"                this.testSuites = testSuites;\n"
"            }\n"
"\n"
"            var TestSuite = function(json) {\n"
"                this.name = json.name;\n"
"                this.time = json.time;\n"
"                var passedTests = new Set();\n"
"                var failedTests = new Set();\n"
"                $.each(json.testCases, function(index, test) {\n"
"                    if (test.failed) {\n"
"                        failedTests.add(test.className + test.name);\n"
"                    } else {\n"
"                        passedTests.add(test.className + test.name);\n"
"                    }\n"
"                });\n"
"                // Interestion of passed and failed test sets is a set of tests that passed on retry\n"
"                var passedOnRetryTests = new Set([...passedTests].filter(x => failedTests.has(x)));\n"
"                this.numPassedOnFirstTry = passedTests.size - passedOnRetryTests.size;\n"
"                this.numFinalFailed = failedTests.size - passedOnRetryTests.size;\n"
"                this.numPassedOnRetry = passedOnRetryTests.size;\n"
"                this.numTotalTests = this.numFinalFailed + this.numPassedOnFirstTry + this.numPassedOnRetry;\n"
"                this.failed = this.numFinalFailed > 0;\n"
"\n"
"                var passedTestCases = [];\n"
"                var passedOnRetryTestCases = [];\n"
"                var failedTestCases = [];\n"
"                $.each(json.testCases, function(index, test) {\n"
"                    var currentTest = new Test(test);\n"
"                    if (failedTests.has(test.className + test.name)) {\n"
"                        if (passedTests.has(test.className + test.name)) {\n"
"                            currentTest.passedOnRetry = true;\n"
"                            passedOnRetryTestCases.push(currentTest);\n"
"                        } else {\n"
"                            currentTest.failedFinal = true;\n"
"                            failedTestCases.push(currentTest);\n"
"                        }\n"
"                    } else {\n"
"                      currentTest.passed = true;\n"
"                        passedTestCases.push(currentTest);\n"
"                    }\n"
"                });\n"
"                passedTestCases.sort(function(a, b) {\n"
"                    return (a.className + a.name).localeCompare(b.className + b.name);\n"
"                });\n"
"                failedTestCases.sort(function(a, b){\n"
"                    return (a.className + a.name).localeCompare(b.className + b.name);\n"
"                });\n"
"                passedOnRetryTestCases.sort(function(a, b) {\n"
"                    if ((a.className + a.name).localeCompare(b.className + b.name) == 0) {\n"
"                        if (a.failed && !b.failed) {\n"
"                            return -1;\n"
"                        } else if (!a.failed && b.failed) {\n"
"                            return 1;\n"
"                        } else {\n"
"                            return 0;\n"
"                        }\n"
"                    } else {\n"
"                        return (a.className + a.name).localeCompare(b.className + b.name);\n"
"                    }\n"
"                });\n"
"\n"
"                var allTestCases = [];\n"
"                allTestCases.push(...failedTestCases);\n"
"                allTestCases.push(...passedOnRetryTestCases);\n"
"                allTestCases.push(...passedTestCases);\n"
"                this.testCases = allTestCases;\n"
"            }\n"
"\n"
"            var Test = function(json) {\n"
"                this.name = json.name;\n"
"                this.className = json.className;\n"
"                this.failed = json.failed;\n"
"                this.video = json.video;\n"
"                this.time = json.time;\n"
"                var errors = [];\n"
"                var artifacts = [];\n"
"                if (json.errors) {\n"
"                    $.each(json.errors, function(index, error) {\n"
"                        errors.push(new TestError(error.message, error.location));\n"
"                    });\n"
"                }\n"
"                this.errors = errors;\n"
"                if (json.artifacts) {\n"
"                    $.each(json.artifacts, function(index, artifact) {\n"
"                        artifacts.push(new TestArtifact(artifact));\n"
"                    });\n"
"                }\n"
"                this.artifacts = artifacts;\n"
"            }\n"
"\n"
"            var TestError = function(message, location) {\n"
"                this.message = message;\n"
"                this.location = location;\n"
"            }\n"
"\n"
"            var TestArtifact = function(filePath) {\n"
"                this.filePath = filePath;\n"
"                //todo interesting stuff here\n"
"            }\n"
"\n"
"            $(document).ready(function() {\n"
"\n"
"                var testReport = new TestReport(json);\n"
"                $('body').append(templates.bodyTemplate(testReport));\n"
"\n"
"                $('.test-suite-details-row-details-button:not([disabled=disabled])').each(function() {\n"
"                    var that = $(this);\n"
"                    var index = that.data(\"index\");\n"
"                    that.click(function() {\n"
"                        that.parent().parent().parent().find('.test-suite-details-error-row-' + index).toggleClass('display-none');\n"
"                        return false;\n"
"                    });\n"
"                });\n"
"\n"
"                $('.test-suite-details-row-artifacts-button:not([disabled=disabled])').each(function() {\n"
"                    var that = $(this);\n"
"                    var index = that.data(\"index\");\n"
"                    that.click(function() {\n"
"                        that.parent().parent().parent().find('.test-suite-details-artifacts-row-' + index).toggleClass('display-none');\n"
"                        return false;\n"
"                    });\n"
"                });\n"
"\n"
"                $('.test-suite-link').each(function() {\n"
"                    var that = $(this);\n"
"                    var index = that.data(\"index\");\n"
"                    that.click(function() {\n"
"                        $('.test-suite-details-table-' + index).toggleClass('display-none');\n"
"                        return false;\n"
"                    });\n"
"                });\n"
"            });\n"
"        </script>\n"
"    </body>\n"
"</html>";

#endif /* BPTestReportHTML_h */
