//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/XCTestManager_DaemonConnectionInterface-Protocol.h>
#import <XCTest/XCTestManager_IDEInterface-Protocol.h>

__attribute__((visibility("hidden")))
@interface _Dummy_ConformingToLegacyProtocolNames : NSObject <XCTestManager_IDEInterface, XCTestManager_DaemonConnectionInterface>
{
}

@end

