//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTTestIdentifier.h>

__attribute__((visibility("hidden")))
@interface _XCTTestIdentifierPlaceholder : XCTTestIdentifier
{
}

- (id)initWithComponents:(id)arg1 options:(unsigned long long)arg2;

@end

