//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTTestIdentifier.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _XCTTestIdentifier_Array : XCTTestIdentifier
{
    NSArray *_components;
    unsigned long long _options;
}

- (void).cxx_destruct;
- (unsigned long long)options;
- (id)components;
- (id)componentAtIndex:(unsigned long long)arg1;
- (unsigned long long)componentCount;
- (id)initWithComponents:(id)arg1 options:(unsigned long long)arg2;

@end

