//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PrivateHeaders/DTXConnectionServices/DTXConnection.h>

@interface DTXConnection (XCTestAdditions)
- (id)xct_makeProxyChannelWithRemoteInterface:(id)arg1 exportedInterface:(id)arg2;
- (void)xct_handleProxyRequestForInterface:(id)arg1 peerInterface:(id)arg2 handler:(id)arg3;
@end

