//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSCopying-Protocol.h>

@class NSDate, NSDictionary;

@protocol MXMInstrumental <NSCopying>
- (_Bool)harvestData:(id *)arg1 error:(id *)arg2;

@optional
- (void)didStopAtContinuousTime:(unsigned long long)arg1 absoluteTime:(unsigned long long)arg2 stopDate:(NSDate *)arg3;
- (void)didStartAtContinuousTime:(unsigned long long)arg1 absoluteTime:(unsigned long long)arg2 startDate:(NSDate *)arg3;
- (void)didStopAtTime:(unsigned long long)arg1 stopDate:(NSDate *)arg2;
- (void)willStop;
- (void)didStartAtTime:(unsigned long long)arg1 startDate:(NSDate *)arg2;
- (void)willStartAtEstimatedTime:(unsigned long long)arg1;
- (_Bool)prepareWithOptions:(NSDictionary *)arg1 error:(id *)arg2;
@end

