//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (XCTFuture)
+ (id)_xcui_errorWithDomain:(id)arg1 code:(long long)arg2 userInfo:(id)arg3 description:(id)arg4 arguments:(struct __va_list_tag [1])arg5;
+ (id)_xcui_errorWithDomain:(id)arg1 code:(long long)arg2 description:(id)arg3;
+ (id)_xcui_error:(long long)arg1 userInfo:(id)arg2 description:(id)arg3;
+ (id)_xcui_error:(long long)arg1 description:(id)arg2;
@property(readonly) _Bool xct_isFutureTimeout;
@property(readonly) _Bool xct_isFutureCancelation;
@property(readonly) _Bool xcui_isRemoteElementSnapshotError;
@property(readonly) _Bool xcui_isApplicationNotRunningError;
- (_Bool)xcui_isUITestingError:(long long)arg1;
@property(readonly) _Bool xct_shouldBeRecordedAsTestFailure;
@end

