//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (XCTestAdditions)
- (void)xct_shuffleWithRandomNumberGenerator:(CDUnknownBlockType)arg1;
- (void)xct_shuffle;
@end

