//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (XCTestAdditions)
+ (id)xct_valueWithCGRect:(struct CGRect)arg1;
@property(readonly) struct CGRect xct_CGRectValue;
- (id)xct_contentDescription;
@end

