//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCUIElementQuery.h>

@class XCElementSnapshot, XCUIApplication;

__attribute__((visibility("hidden")))
@interface XCApplicationQuery : XCUIElementQuery
{
    XCUIApplication *_application;
    XCElementSnapshot *_lastSnapshot;
}

- (void).cxx_destruct;
@property(retain) XCElementSnapshot *lastSnapshot; // @synthesize lastSnapshot=_lastSnapshot;
- (id)application;
- (id)initWithApplication:(id)arg1;
- (void)dealloc;

@end

