//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/XCUIAccessibilityInterface-Protocol.h>

@class NSMutableDictionary, NSString, XCAccessibilityElement;
@protocol OS_dispatch_queue, XCUIApplicationProcessTracker, XCUIDevice, XCUIRemoteAccessibilityInterface;

@interface XCAXClient_iOS : NSObject <XCUIAccessibilityInterface>
{
    id <XCUIApplicationProcessTracker> _applicationProcessTracker;
    id <XCUIRemoteAccessibilityInterface> _remoteAccessibilityInterface;
    id <XCUIDevice> _device;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_userTestingNotificationHandlers;
    NSMutableDictionary *_oneShotUserTestingNotificationHandlers;
    NSMutableDictionary *_cachedAccessibilityLoadedValuesForPIDs;
}

- (void).cxx_destruct;
@property(readonly) NSMutableDictionary *cachedAccessibilityLoadedValuesForPIDs; // @synthesize cachedAccessibilityLoadedValuesForPIDs=_cachedAccessibilityLoadedValuesForPIDs;
@property(readonly) NSMutableDictionary *oneShotUserTestingNotificationHandlers; // @synthesize oneShotUserTestingNotificationHandlers=_oneShotUserTestingNotificationHandlers;
@property(readonly) NSMutableDictionary *userTestingNotificationHandlers; // @synthesize userTestingNotificationHandlers=_userTestingNotificationHandlers;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) __weak id <XCUIDevice> device; // @synthesize device=_device;
@property(readonly) id <XCUIRemoteAccessibilityInterface> remoteAccessibilityInterface; // @synthesize remoteAccessibilityInterface=_remoteAccessibilityInterface;
@property(readonly) id <XCUIApplicationProcessTracker> applicationProcessTracker; // @synthesize applicationProcessTracker=_applicationProcessTracker;
- (id)accessibilityElementForElementAtPoint:(struct CGPoint)arg1 error:(id *)arg2;
- (void)performWhenMenuOpens:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)removeObserver:(id)arg1 forAXNotification:(id)arg2;
- (id)addObserverForAXNotification:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)unregisterForAXNotificationsForApplicationWithPID:(int)arg1;
- (void)registerForAXNotificationsForApplicationWithPID:(int)arg1 timeout:(double)arg2 completion:(CDUnknownBlockType)arg3;
@property double AXTimeout;
- (_Bool)_setAXTimeout:(double)arg1 error:(id *)arg2;
- (id)localizableStringsDataForActiveApplications;
- (_Bool)performAction:(id)arg1 onElement:(id)arg2 value:(id)arg3 error:(id *)arg4;
- (id)parameterizedAttribute:(id)arg1 forElement:(id)arg2 parameter:(id)arg3 error:(id *)arg4;
- (_Bool)setAttribute:(id)arg1 value:(id)arg2 element:(id)arg3 outError:(id *)arg4;
@property(readonly) _Bool allowsRemoteAccess;
- (id)valuesForPrivilegedAttributes:(id)arg1 forElement:(id)arg2 error:(id *)arg3;
@property(readonly) _Bool providesValuesForPrivilegedAttributes;
- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (id)requestSnapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 error:(id *)arg4;
- (id)defaultParameters;
- (void)notifyWhenViewControllerViewDidDisappearReply:(CDUnknownBlockType)arg1;
- (id)viewDidAppearExpectationForElement:(id)arg1 viewControllerName:(id)arg2;
- (void)notifyWhenNoAnimationsAreActiveForApplication:(id)arg1 reply:(CDUnknownBlockType)arg2;
@property(readonly) _Bool supportsAnimationsInactiveNotifications;
- (void)notifyWhenEventLoopIsIdleForApplication:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (id)_snapshotsForInterruptingElementsPresentedByApplication:(id)arg1;
- (id)_hittableElementsInSnapshots:(id)arg1;
- (id)_activeForegroundApplicationsWithPotentiallyInterruptingUI;
- (id)interruptingUIElementsAffectingSnapshot:(id)arg1 checkForHandledElement:(id)arg2 containsHandledElement:(_Bool *)arg3;
- (_Bool)isMacCatalystForPID:(int)arg1;
@property(readonly) _Bool hasBannerNotificationIsStickyAttribute;
@property(readonly) _Bool usePointTransformationsForFrameConversions;
@property(readonly) _Bool supportsHostedViewCoordinateTransformations;
@property(readonly) _Bool axNotificationsIncludeElement;
- (void)handleAccessibilityNotification:(int)arg1 fromElement:(id)arg2 payload:(id)arg3;
- (void)notifyOnNextOccurrenceOfUserTestingEvent:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_removeUserTestNotificationHandlerForToken:(id)arg1;
- (id)_addUserTestNotificationHandler:(CDUnknownBlockType)arg1;
- (void)_handleUserTestingNotificationFromElement:(id)arg1 withPayload:(id)arg2;
- (id)hitTestElement:(id)arg1 withPoint:(struct CGPoint)arg2 error:(id *)arg3;
- (_Bool)cachedAccessibilityLoadedValueForPID:(int)arg1;
- (id)activeApplications;
@property(readonly, nonatomic) XCAccessibilityElement *systemApplication;
- (_Bool)enableFauxCollectionViewCells:(id *)arg1;
- (_Bool)loadAccessibility:(id *)arg1;
- (_Bool)_registerForAXNotification:(int)arg1 error:(id *)arg2;
- (_Bool)_loadAccessibility:(id *)arg1;
- (id)initWithApplicationProcessTracker:(id)arg1 remoteAccessibilityInterface:(id)arg2 device:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

