//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface XCSourceCodeTreeNodeEnumerator : NSObject
{
    NSMutableArray *_remainingNodes;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *remainingNodes; // @synthesize remainingNodes=_remainingNodes;
- (id)nextObject;
- (id)initWithNode:(id)arg1;

@end

