//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XCTActivityAggregationRecord : NSObject
{
    double _totalTime;
    double _timeMinusSubactivities;
}

@property double timeMinusSubactivities; // @synthesize timeMinusSubactivities=_timeMinusSubactivities;
@property double totalTime; // @synthesize totalTime=_totalTime;

@end

