//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSSecureCoding-Protocol.h>

@class NSString;

@interface XCTAggregateSuiteRunStatisticsRecord : NSObject <NSSecureCoding>
{
    NSString *_suiteName;
    unsigned long long _executionCount;
    unsigned long long _skipCount;
    unsigned long long _expectedFailureCount;
    unsigned long long _failureCount;
    unsigned long long _unexpectedExceptionCount;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly) unsigned long long unexpectedExceptionCount; // @synthesize unexpectedExceptionCount=_unexpectedExceptionCount;
@property(readonly) unsigned long long failureCount; // @synthesize failureCount=_failureCount;
@property(readonly) unsigned long long expectedFailureCount; // @synthesize expectedFailureCount=_expectedFailureCount;
@property(readonly) unsigned long long skipCount; // @synthesize skipCount=_skipCount;
@property(readonly) unsigned long long executionCount; // @synthesize executionCount=_executionCount;
@property(readonly) NSString *suiteName; // @synthesize suiteName=_suiteName;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqualToStatisticsRecord:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSuiteName:(id)arg1 executionCount:(unsigned long long)arg2 skipCount:(unsigned long long)arg3 expectedFailureCount:(unsigned long long)arg4 failureCount:(unsigned long long)arg5 unexpectedExceptionCount:(unsigned long long)arg6;
- (id)initWithSuiteName:(id)arg1 executionCount:(unsigned long long)arg2 skipCount:(unsigned long long)arg3 failureCount:(unsigned long long)arg4 unexpectedExceptionCount:(unsigned long long)arg5;

@end

