//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface XCTActivityAggregationRecord : NSObject
{
    double _totalTime;
    double _timeMinusSubactivities;
}

@property double timeMinusSubactivities; // @synthesize timeMinusSubactivities=_timeMinusSubactivities;
@property double totalTime; // @synthesize totalTime=_totalTime;

@end

