//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTestExpectation.h>

#import <XCTest/XCTestExpectationDelegate-Protocol.h>

@class NSArray, NSString;

@interface XCTCompoundExpectation : XCTestExpectation <XCTestExpectationDelegate>
{
    unsigned long long _logicalType;
    NSArray *_subexpectations;
}

- (void).cxx_destruct;
@property(readonly, copy) NSArray *subexpectations; // @synthesize subexpectations=_subexpectations;
@property(readonly) unsigned long long logicalType; // @synthesize logicalType=_logicalType;
- (void)didFulfillExpectation:(id)arg1;
- (void)cleanup;
- (_Bool)_queue_validateSubexpectationsFulfillment;
- (void)_updateFulfilledState;
- (void)dealloc;
- (id)initWithLogicalType:(unsigned long long)arg1 subexpectations:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

