//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTestExpectation.h>

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface XCTDarwinNotificationExpectation : XCTestExpectation
{
    _Bool _hasCleanedUp;
    int _notifyToken;
    CDUnknownBlockType _handler;
    NSString *_notificationName;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
@property _Bool hasCleanedUp; // @synthesize hasCleanedUp=_hasCleanedUp;
@property int notifyToken; // @synthesize notifyToken=_notifyToken;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, copy) NSString *notificationName; // @synthesize notificationName=_notificationName;
- (void)cleanup;
- (void)_handleNotification;
@property(copy) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (id)initWithNotificationName:(id)arg1;
- (void)dealloc;

@end

