//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/XCTTelemetryLogging-Protocol.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_group;

@interface XCTDaemonTelemetryLogger : NSObject <XCTTelemetryLogging>
{
    _Bool _isUITest;
    CDUnknownBlockType _eventDataSink;
    NSString *_sessionUUID;
    NSString *_osVersion;
    NSString *_hardwareModel;
    NSString *_frameworkVariant;
    NSMutableDictionary *_localEvents;
    NSObject<OS_dispatch_group> *_submissionGroup;
}

+ (_Bool)telemetrySupported;
- (void).cxx_destruct;
@property(readonly) NSObject<OS_dispatch_group> *submissionGroup; // @synthesize submissionGroup=_submissionGroup;
@property(retain) NSMutableDictionary *localEvents; // @synthesize localEvents=_localEvents;
@property(readonly) _Bool isUITest; // @synthesize isUITest=_isUITest;
@property(readonly, copy) NSString *frameworkVariant; // @synthesize frameworkVariant=_frameworkVariant;
@property(readonly, copy) NSString *hardwareModel; // @synthesize hardwareModel=_hardwareModel;
@property(readonly, copy) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(readonly, copy) NSString *sessionUUID; // @synthesize sessionUUID=_sessionUUID;
@property(readonly, copy) CDUnknownBlockType eventDataSink; // @synthesize eventDataSink=_eventDataSink;
- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (void)logUsageOfFunction:(id)arg1;
- (void)logUsageOfClass:(id)arg1 method:(id)arg2;
- (void)logEventWithName:(id)arg1;
- (id)initWithSessionUUID:(id)arg1 OSVersion:(id)arg2 hardwareModel:(id)arg3 frameworkVariant:(id)arg4 isUITest:(_Bool)arg5 eventDataSink:(CDUnknownBlockType)arg6;
- (id)initWithEventDataSink:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

