//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface XCTestConfigurationLoader : NSObject
{
    NSURL *_testConfigurationURLFromEnvironment;
}

- (void).cxx_destruct;
@property(readonly, copy) NSURL *testConfigurationURLFromEnvironment; // @synthesize testConfigurationURLFromEnvironment=_testConfigurationURLFromEnvironment;
- (id)_mostRecentFileInDirectory:(id)arg1 withExtension:(id)arg2;
- (id)_mostRecentTestBundle;
- (id)_testConfigurationFromURL:(id)arg1;
- (id)_synthesizedConfigurationForTestBundle:(id)arg1;
- (id)_configurationForTestBundle:(id)arg1;
- (id)_loadTestConfigurationFromTemporaryDirectoryWithDidFind:(_Bool *)arg1;
- (id)_loadTestConfigurationFromEnvironmentURL:(id)arg1;
- (id)loadTestConfigurationFromEnvironmentWithDidSpecify:(_Bool *)arg1;
- (id)loadTestConfiguration;
- (id)init;
- (id)initWithTestConfigurationURLFromEnvironment:(id)arg1;

@end

