//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject<OS_dispatch_queue>, NSString, _XCTestExpectationImplementation;

@interface XCTestExpectation : NSObject
{
    id _internalImplementation;
}

+ (id)expectationWithDescription:(id)arg1;
@property(readonly) _XCTestExpectationImplementation *internalImplementation; // @synthesize internalImplementation=_internalImplementation;
- (void)cleanup;
@property _Bool hasBeenWaitedOn;
@property id <XCTestExpectationDelegate> delegate;
@property(readonly, copy) NSArray *fulfillCallStackReturnAddresses;
@property(readonly, copy) NSArray *creationCallStackReturnAddresses;
@property(readonly) _Bool fulfilled;
@property _Bool hasInverseBehavior;
@property(getter=isInverted) _Bool inverted;
@property(nonatomic) _Bool assertForOverFulfill;
@property(nonatomic) unsigned long long expectedFulfillmentCount;
@property(nonatomic) unsigned long long fulfillmentCount;
@property(readonly) unsigned long long fulfillmentToken;
@property(readonly) unsigned long long creationToken;
- (void)_queue_fulfillWithCallStackReturnAddresses:(id)arg1;
- (void)fulfill;
@property(copy) NSString *expectationDescription;
- (id)description;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
- (id)initWithDescription:(id)arg1;
- (id)init;
- (void)dealloc;

@end

