//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTest.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, XCTTestIdentifier, XCTestConfiguration;

@interface XCTestSuite : XCTest
{
    XCTTestIdentifier *_identifier;
    NSString *_name;
    NSMutableArray *_mutableTests;
    XCTestConfiguration *_testConfiguration;
    NSMutableDictionary *_mutableActivityAggregateStatistics;
}

+ (id)testClassSuitesForTestIdentifiers:(id)arg1 skippingTestIdentifiers:(id)arg2 randomNumberGenerator:(CDUnknownBlockType)arg3;
+ (id)testSuiteForTestConfiguration:(id)arg1;
+ (id)defaultTestSuite;
+ (id)allTests;
+ (id)testSuiteForTestCaseClass:(Class)arg1;
+ (id)testSuiteForTestCaseWithName:(id)arg1;
+ (id)testSuiteForBundlePath:(id)arg1;
+ (id)suiteForBundleCache;
+ (void)invalidateCache;
+ (id)_suiteForBundleCache;
+ (id)emptyTestSuiteNamedFromPath:(id)arg1;
+ (id)testSuiteWithName:(id)arg1;
- (void).cxx_destruct;
@property(readonly) NSMutableDictionary *mutableActivityAggregateStatistics; // @synthesize mutableActivityAggregateStatistics=_mutableActivityAggregateStatistics;
@property(retain) XCTestConfiguration *testConfiguration; // @synthesize testConfiguration=_testConfiguration;
@property(retain) NSMutableArray *mutableTests; // @synthesize mutableTests=_mutableTests;
@property(copy) NSString *name; // @synthesize name=_name;
- (id)_identifier;
- (id)_initWithTestConfiguration:(id)arg1;
- (void)_applyRandomExecutionOrderingWithGenerator:(CDUnknownBlockType)arg1;
- (void)_sortTestsUsingDefaultExecutionOrdering;
- (long long)defaultExecutionOrderCompare:(id)arg1;
@property(readonly) NSDictionary *activityAggregateStatistics;
- (void)_mergeActivityStatistics:(id)arg1;
- (void)runTestBasedOnRerunPolicy:(id)arg1 testRun:(id)arg2;
- (void)performTest:(id)arg1;
- (void)_performProtectedSectionForTest:(id)arg1 testSection:(CDUnknownBlockType)arg2;
- (void)_recordUnexpectedFailureForTestRun:(id)arg1 description:(id)arg2 exception:(id)arg3;
- (void)handleIssue:(id)arg1;
- (void)recordFailureWithDescription:(id)arg1 inFile:(id)arg2 atLine:(unsigned long long)arg3 expected:(_Bool)arg4;
- (Class)testRunClass;
- (Class)_requiredTestRunBaseClass;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)testCaseCount;
- (void)setTests:(id)arg1;
@property(readonly, copy) NSArray *tests;
- (void)addTest:(id)arg1;
- (id)_testSuiteWithIdentifier:(id)arg1;
- (id)description;
- (id)initWithName:(id)arg1;
- (id)init;
- (void)removeTestsWithIdentifierInSet:(id)arg1;

@end

