//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, XCTExpectedFailureOptions, XCTSourceCodeContext;

@interface XCTExpectedFailureContext : NSObject
{
    _Bool _hasMatchedIssues;
    XCTExpectedFailureOptions *_options;
    NSString *_failureReason;
    XCTSourceCodeContext *_sourceCodeContext;
    unsigned long long _threadId;
}

- (void).cxx_destruct;
@property(readonly) unsigned long long threadId; // @synthesize threadId=_threadId;
@property _Bool hasMatchedIssues; // @synthesize hasMatchedIssues=_hasMatchedIssues;
@property(retain) XCTSourceCodeContext *sourceCodeContext; // @synthesize sourceCodeContext=_sourceCodeContext;
@property(readonly, copy) NSString *failureReason; // @synthesize failureReason=_failureReason;
@property(readonly, copy) XCTExpectedFailureOptions *options; // @synthesize options=_options;
- (_Bool)matchesIssue:(id)arg1;
- (id)initWithFailureReason:(id)arg1 options:(id)arg2;

@end

