//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTAutomationSupport/XCTImageEncoding.h>

@interface XCTImageEncoding (XCTImageQuality)
+ (double)compressionQualityForQuality:(long long)arg1;
+ (id)uniformTypeIdentifierForQuality:(long long)arg1;
+ (id)systemScreenshotEncoding;
+ (_Bool)isValidCompressionQuality:(double)arg1 andCompressionQualityObject:(id)arg2;
+ (double)systemScreenshotCompressionQuality;
+ (id)systemScreenshotUniformTypeIdentifier;
- (id)initWithImageQuality:(long long)arg1;
@end

