//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PrivateHeaders/XCTest/XCTMessagingRole_ProcessMonitoring-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_TestExecution-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_TestExecution_Legacy-Protocol.h>
#import <PrivateHeaders/XCTest/_XCTMessaging_VoidProtocol-Protocol.h>

@protocol XCTMessagingChannel_IDEToRunner <XCTMessagingRole_TestExecution, XCTMessagingRole_TestExecution_Legacy, XCTMessagingRole_ProcessMonitoring, _XCTMessaging_VoidProtocol>

@optional
- (void)__dummy_method_to_work_around_68987191;
@end

