//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/MXMInstrumental-Protocol.h>

@class XCTPerformanceMeasurementTimestamp;
@protocol XCTMetric;

@interface XCTMetricInstrumentalAdapter : NSObject <MXMInstrumental>
{
    XCTPerformanceMeasurementTimestamp *_startTimestamp;
    XCTPerformanceMeasurementTimestamp *_stopTimestamp;
    id <XCTMetric> _metric;
}

+ (void)addMetricToMeasurements:(id)arg1 sampleTag:(id)arg2 identifier:(id)arg3 displayName:(id)arg4 measurements:(id)arg5 skipConversion:(_Bool)arg6 polarity:(long long)arg7;
- (void).cxx_destruct;
@property(retain, nonatomic) id <XCTMetric> metric; // @synthesize metric=_metric;
- (_Bool)harvestData:(id *)arg1 error:(id *)arg2;
- (void)didStopAtContinuousTime:(unsigned long long)arg1 absoluteTime:(unsigned long long)arg2 stopDate:(id)arg3;
- (void)didStopAtTime:(unsigned long long)arg1 stopDate:(id)arg2;
- (void)didStartAtContinuousTime:(unsigned long long)arg1 absoluteTime:(unsigned long long)arg2 startDate:(id)arg3;
- (void)didStartAtTime:(unsigned long long)arg1 startDate:(id)arg2;
- (void)willStartAtEstimatedTime:(unsigned long long)arg1;
- (_Bool)prepareWithOptions:(id)arg1 error:(id *)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithMetric:(id)arg1;

@end

