//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PrivateHeaders/XCTest/XCTMessagingRole_ActivityReporting-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_ActivityReporting_Legacy-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_DebugLogging-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_PerformanceMeasurementReporting-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_PerformanceMeasurementReporting_Legacy-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_SelfDiagnosisIssueReporting-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_TestReporting-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_TestReporting_Legacy-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_UIAutomation-Protocol.h>
#import <PrivateHeaders/XCTest/_XCTMessaging_VoidProtocol-Protocol.h>

@protocol XCTMessagingChannel_RunnerToIDE <XCTMessagingRole_DebugLogging, XCTMessagingRole_TestReporting, XCTMessagingRole_TestReporting_Legacy, XCTMessagingRole_SelfDiagnosisIssueReporting, XCTMessagingRole_UIAutomation, XCTMessagingRole_ActivityReporting, XCTMessagingRole_ActivityReporting_Legacy, XCTMessagingRole_PerformanceMeasurementReporting, XCTMessagingRole_PerformanceMeasurementReporting_Legacy, _XCTMessaging_VoidProtocol>

@optional
- (void)__dummy_method_to_work_around_68987191;
@end

