//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSSet;

@protocol XCTMessagingRole_TestExecution_Legacy
- (id)_IDE_executeTestIdentifiers:(NSSet *)arg1 skippingTestIdentifiers:(NSSet *)arg2;
- (id)_IDE_fetchDiscoveredTestClasses;
@end

