//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PrivateHeaders/XCTest/XCTMessagingRole_ControlSessionInitiation-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_DiagnosticsCollection-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_RunnerSessionInitiation-Protocol.h>
#import <PrivateHeaders/XCTest/XCTMessagingRole_UIRecordingControl-Protocol.h>
#import <PrivateHeaders/XCTest/_XCTMessaging_VoidProtocol-Protocol.h>

@protocol XCTMessagingChannel_IDEToDaemon <XCTMessagingRole_RunnerSessionInitiation, XCTMessagingRole_ControlSessionInitiation, XCTMessagingRole_UIRecordingControl, XCTMessagingRole_DiagnosticsCollection, _XCTMessaging_VoidProtocol>

@optional
- (void)__dummy_method_to_work_around_68987191;
@end

