//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface XCTMeasurement : NSObject
{
    NSString *_identifier;
    NSString *_units;
    NSString *_name;
    NSDictionary *_baseline;
    NSDictionary *_defaultBaseline;
    NSArray *_measurements;
    long long _polarity;
}

- (void).cxx_destruct;
@property long long polarity; // @synthesize polarity=_polarity;
@property(copy) NSArray *measurements; // @synthesize measurements=_measurements;
@property(copy) NSDictionary *defaultBaseline; // @synthesize defaultBaseline=_defaultBaseline;
@property(copy) NSDictionary *baseline; // @synthesize baseline=_baseline;
@property(copy) NSString *name; // @synthesize name=_name;
@property(copy) NSString *units; // @synthesize units=_units;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
- (id)init;

@end

