//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTMessagingRole_BundleRequesting-Protocol.h>
#import <XCTest/XCTMessagingRole_CapabilityExchange-Protocol.h>
#import <XCTest/XCTMessagingRole_EventSynthesis-Protocol.h>
#import <XCTest/XCTMessagingRole_ForcePressureSupportQuerying-Protocol.h>
#import <XCTest/XCTMessagingRole_MemoryTesting-Protocol.h>
#import <XCTest/XCTMessagingRole_ProtectedResourceAuthorization-Protocol.h>
#import <XCTest/XCTMessagingRole_SiriAutomation-Protocol.h>
#import <XCTest/_XCTMessaging_VoidProtocol-Protocol.h>

@protocol XCTMessagingChannel_RunnerToDaemon <XCTMessagingRole_ProtectedResourceAuthorization, XCTMessagingRole_CapabilityExchange, XCTMessagingRole_EventSynthesis, XCTMessagingRole_SiriAutomation, XCTMessagingRole_MemoryTesting, XCTMessagingRole_BundleRequesting, XCTMessagingRole_ForcePressureSupportQuerying, _XCTMessaging_VoidProtocol>

@optional
- (void)__dummy_method_to_work_around_68987191;
@end

