//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSCopying-Protocol.h>
#import <XCTest/NSObject-Protocol.h>

@class NSArray, XCTPerformanceMeasurementTimestamp;

@protocol XCTMetric <NSCopying, NSObject>
- (NSArray *)reportMeasurementsFromStartTime:(XCTPerformanceMeasurementTimestamp *)arg1 toEndTime:(XCTPerformanceMeasurementTimestamp *)arg2 error:(id *)arg3;

@optional
- (void)didStopMeasuring;
- (void)willBeginMeasuring;
@end

