//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSString, XCTestExpectation;

@interface XCTPromise : NSObject
{
    struct atomic_flag _promiseFulfilled;
    NSString *_promiseDescription;
    id _value;
    NSError *_error;
    XCTestExpectation *_expectation;
}

- (void).cxx_destruct;
@property(readonly) struct atomic_flag promiseFulfilled; // @synthesize promiseFulfilled=_promiseFulfilled;
@property(readonly) XCTestExpectation *expectation; // @synthesize expectation=_expectation;
@property(retain) NSError *error; // @synthesize error=_error;
@property(retain) id value; // @synthesize value=_value;
@property(readonly, copy) NSString *promiseDescription; // @synthesize promiseDescription=_promiseDescription;
- (void)fulfillWithValue:(id)arg1 error:(id)arg2;
- (void)fulfillWithError:(id)arg1;
- (void)fulfillWithValue:(id)arg1;
- (id)initWithDescription:(id)arg1;

@end

