//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol XCTSwiftErrorObservation_Overlay

@optional
+ (XCTIssue * (^)(void))_observeErrors;
+ (_Bool)_installErrorObserver;
@end

