//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class XCTSourceCodeSymbolInfo;

@protocol XCTSymbolInfoProviding <NSObject>
- (XCTSourceCodeSymbolInfo *)symbolInfoForAddressInCurrentProcess:(unsigned long long)arg1 error:(id *)arg2;
@end

