//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface XCTSymbolicationService : NSObject
{
}

+ (void)pushSharedSymbolicationService:(id)arg1 forScope:(CDUnknownBlockType)arg2;
+ (void)setSharedService:(id)arg1;
+ (id)sharedService;

@end

