//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSSecureCoding-Protocol.h>

@class NSArray, XCTSourceCodeLocation;

@interface XCTSourceCodeContext : NSObject <NSSecureCoding>
{
    NSArray *_callStack;
    XCTSourceCodeLocation *_location;
}

+ (_Bool)supportsSecureCoding;
+ (id)sourceCodeFramesFromCallStackReturnAddresses:(id)arg1;
- (void).cxx_destruct;
@property(readonly) XCTSourceCodeLocation *location; // @synthesize location=_location;
@property(readonly, copy) NSArray *callStack; // @synthesize callStack=_callStack;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithLocation:(id)arg1;
- (id)initWithCallStackAddresses:(id)arg1 location:(id)arg2;
- (id)initWithCallStack:(id)arg1 location:(id)arg2;

@end

