//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSObject, XCTTestIdentifierSet;
@protocol OS_dispatch_queue, XCTTestSchedulerDelegate, XCTTestSchedulerWorker;

@protocol XCTTestScheduler
@property(retain) NSObject<OS_dispatch_queue> *delegateQueue;
@property __weak id <XCTTestSchedulerDelegate> delegate;
@property(retain) NSObject<OS_dispatch_queue> *workerQueue;
- (void)startWithTestIdentifiersToRun:(XCTTestIdentifierSet *)arg1 testIdentifiersToSkip:(XCTTestIdentifierSet *)arg2;
- (void)workerDidBecomeAvailable:(id <XCTTestSchedulerWorker>)arg1;
@end

