//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class NSString;

@protocol XCTTelemetryLogging <NSObject>
- (void)flushWithCompletion:(void (^)(void))arg1;
- (void)logUsageOfFunction:(NSString *)arg1;
- (void)logUsageOfClass:(NSString *)arg1 method:(NSString *)arg2;
- (void)logEventWithName:(NSString *)arg1;
@end

