//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTTestSchedulerWorker-Protocol.h>

@protocol XCTTestWorker <XCTTestSchedulerWorker>
- (void)fetchDiscoveredTestClasses:(void (^)(XCTTestIdentifierSet *, NSError *))arg1;
@end

