//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class NSObject, XCTTestIdentifierSet;
@protocol OS_dispatch_queue;

@protocol XCTTestSchedulerWorker <NSObject>
- (void)shutdown;
- (void)executeTestIdentifiers:(XCTTestIdentifierSet *)arg1 skippingTestIdentifiers:(XCTTestIdentifierSet *)arg2 completionHandler:(void (^)(NSError *))arg3 completionQueue:(NSObject<OS_dispatch_queue> *)arg4;
@end

