//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSCopying-Protocol.h>

@class NSMutableSet, XCTTestIdentifierSet;

@interface XCTTestIdentifierSetBuilder : NSObject <NSCopying>
{
    NSMutableSet *_testIdentifiers;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)addTestIdentifierWithLegacyStringRepresentation:(id)arg1 includingSwiftCounterpart:(_Bool)arg2;
- (void)minusBuilder:(id)arg1;
- (void)minusSet:(id)arg1;
- (void)unionBuilder:(id)arg1;
- (void)unionSet:(id)arg1;
- (void)removeAllTestIdentifiers;
- (void)removeTestIdentifier:(id)arg1;
- (void)addTestIdentifier:(id)arg1;
- (_Bool)containsTestIdentifier:(id)arg1;
@property(readonly) XCTTestIdentifierSet *testIdentifierSet;
@property(readonly) unsigned long long count;
- (id)initWithTestIdentifierSet:(id)arg1;
- (id)initWithSet:(id)arg1;
- (id)initWithArray:(id)arg1;
- (id)initWithTestIdentifier:(id)arg1;
- (id)init;

@end

