//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/XCUIInterruptionMonitoring-Protocol.h>

@class NSString;

@interface XCUIInterruptionMonitor : NSObject <XCUIInterruptionMonitoring>
{
    _Bool _didHandleUIInterruption;
    long long _platform;
}

+ (CDUnknownBlockType)defaultInterruptionHandler_iOS;
@property(readonly) long long platform; // @synthesize platform=_platform;
@property _Bool didHandleUIInterruption; // @synthesize didHandleUIInterruption=_didHandleUIInterruption;
- (_Bool)handleInterruptingElement:(id)arg1;
- (void)removeInterruptionHandlerWithIdentifier:(id)arg1;
- (id)addInterruptionHandlerWithDescription:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)initWithPlatform:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

