//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSCopying-Protocol.h>

__attribute__((visibility("hidden")))
@interface XCUITransformParameters : NSObject <NSCopying>
{
    unsigned long long _windowID;
    unsigned long long _displayID;
}

+ (id)transformParametersWithWindowID:(unsigned long long)arg1 displayID:(unsigned long long)arg2;
@property(readonly) unsigned long long displayID; // @synthesize displayID=_displayID;
@property(readonly) unsigned long long windowID; // @synthesize windowID=_windowID;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

