//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;
@protocol XCUIApplicationRegistryProvider;

@interface XCUIApplicationRegistry : NSObject
{
    NSDictionary *_testDependencies;
    NSDictionary *_userOverrides;
    id <XCUIApplicationRegistryProvider> _platformProvider;
}

- (void).cxx_destruct;
@property(retain) id <XCUIApplicationRegistryProvider> platformProvider; // @synthesize platformProvider=_platformProvider;
@property(copy) NSDictionary *userOverrides; // @synthesize userOverrides=_userOverrides;
@property(copy) NSDictionary *testDependencies; // @synthesize testDependencies=_testDependencies;
- (_Bool)testDependencyExistsForApplicationAtURL:(id)arg1;
- (id)recordForApplicationWithBundleIdentifier:(id)arg1 error:(id *)arg2;
- (id)_constructRecordMapFromRawMap:(id)arg1 isTestDependencyMap:(_Bool)arg2;
- (id)initWithTestDependencies:(id)arg1 userOverrides:(id)arg2;

@end

