//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface XCUIApplicationRegistryRecord : NSObject
{
    _Bool _isTestDependency;
    NSURL *_URL;
    NSString *_bundleIdentifier;
}

- (void).cxx_destruct;
@property(readonly) _Bool isTestDependency; // @synthesize isTestDependency=_isTestDependency;
@property(readonly, copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly, copy) NSURL *URL; // @synthesize URL=_URL;
- (id)initWithURL:(id)arg1 bundleIdentifier:(id)arg2 isTestDependency:(_Bool)arg3;

@end

