//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCUICoordinate.h>

__attribute__((visibility("hidden")))
@interface XCUIElementHitPointCoordinate : XCUICoordinate
{
}

- (id)description;
- (struct CGPoint)screenPoint;
- (id)initWithCoordinate:(id)arg1 pointsOffset:(struct CGVector)arg2;
- (id)initWithElement:(id)arg1 normalizedOffset:(struct CGVector)arg2;
- (id)initWithElement:(id)arg1;

@end

