//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class NSData, XCAccessibilityElement;

@protocol XCUIAXNotificationHandling <NSObject>
@property(readonly) _Bool axNotificationsIncludeElement;
- (void)handleAccessibilityNotification:(int)arg1 fromElement:(XCAccessibilityElement *)arg2 payload:(NSData *)arg3;
@end

