//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCUIElementAttributes-Protocol.h>

@class NSArray, NSDictionary;

@protocol XCUIElementSnapshot <XCUIElementAttributes>
@property(readonly, copy) NSDictionary *dictionaryRepresentation;
@property(readonly) NSArray *children;
@end

