//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, XCUIApplication;
@protocol XCUIDevice, XCUIRemoteSiriInterface;

@interface XCUISiriService : NSObject
{
    XCUIApplication *_siriApplication;
    id <XCUIDevice> _device;
    id <XCUIRemoteSiriInterface> _remoteSiriInterface;
}

- (void).cxx_destruct;
@property(readonly) id <XCUIRemoteSiriInterface> remoteSiriInterface; // @synthesize remoteSiriInterface=_remoteSiriInterface;
@property(readonly) id <XCUIDevice> device; // @synthesize device=_device;
@property(readonly) XCUIApplication *siriApplication; // @synthesize siriApplication=_siriApplication;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)_waitForActivation;
- (void)_assertSiriEnabled;
- (unsigned long long)_expectedStateForActivate;
- (id)_siriBundleIdentifier;
- (_Bool)_usesLegacySiriViewService;
@property(readonly, getter=isEnabled) _Bool enabled;
- (void)injectVoiceRecognitionAudioInputPaths:(id)arg1;
- (void)injectAssistantRecognitionStrings:(id)arg1;
- (void)activateWithVoiceRecognitionText:(id)arg1;
@property(readonly, copy) NSString *debugDescription;
- (id)initWithDevice:(id)arg1 remoteSiriInterface:(id)arg2;

@end

