//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class NSString, XCUIElement;
@protocol NSObject;

@protocol XCUIInterruptionMonitoring <NSObject>
@property _Bool didHandleUIInterruption;
- (_Bool)handleInterruptingElement:(XCUIElement *)arg1;
- (void)removeInterruptionHandlerWithIdentifier:(id <NSObject>)arg1;
- (id <NSObject>)addInterruptionHandlerWithDescription:(NSString *)arg1 block:(_Bool (^)(XCUIElement *))arg2;
@end

