//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class NSArray, NSString, NSURL;

@protocol XCUIRemoteSiriInterface <NSObject>
@property(readonly) _Bool supportsInjectingVoiceRecognitionAudioInputPaths;
@property(readonly) _Bool supportsStartingSiriUIRequestWithAudioFileURL;
- (void)injectVoiceRecognitionAudioInputPaths:(NSArray *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)injectAssistantRecognitionStrings:(NSArray *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)startSiriUIRequestWithAudioFileURL:(NSURL *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)startSiriUIRequestWithText:(NSString *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)requestSiriEnabledStatus:(void (^)(_Bool, NSError *))arg1;
@end

