//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, UIImage, XCTImage;

@interface XCUIScreenshot : NSObject
{
    XCTImage *_internalImage;
}

+ (id)emptyScreenshot;
- (void).cxx_destruct;
@property(retain) XCTImage *internalImage; // @synthesize internalImage=_internalImage;
- (id)debugQuickLookObject;
@property(readonly, copy) NSData *PNGRepresentation;
@property(readonly, copy) UIImage *image;
- (id)initWithImage:(id)arg1;

@end

