//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class XCTImageEncoding;

@protocol XCUIScreenDataSource <NSObject>
@property(readonly, nonatomic) _Bool supportsHEICImageEncoding;
- (void)requestScreenshotOfScreenWithID:(long long)arg1 withRect:(struct CGRect)arg2 encoding:(XCTImageEncoding *)arg3 withReply:(void (^)(XCTImage *, NSError *))arg4;
- (void)requestScaleForScreenWithIdentifier:(long long)arg1 completion:(void (^)(double, NSError *))arg2;
- (void)requestScreenIdentifiersWithCompletion:(void (^)(NSArray *, NSError *))arg1;
@end

