//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 11 2021 09:30:43).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString, XCUIApplicationSpecifier;
@protocol XCUIApplicationPlatformServicesProviderDelegate;

@protocol XCUIPlatformApplicationServicesProviding <NSObject>
@property __weak id <XCUIApplicationPlatformServicesProviderDelegate> platformApplicationServicesProviderDelegate;
- (void)requestApplicationSpecifierForPID:(int)arg1 reply:(void (^)(XCUIApplicationSpecifier *, NSError *))arg2;
- (void)terminateApplicationWithBundleID:(NSString *)arg1 pid:(int)arg2 completion:(void (^)(_Bool, NSError *))arg3;
- (void)launchApplicationWithPath:(NSString *)arg1 bundleID:(NSString *)arg2 arguments:(NSArray *)arg3 environment:(NSDictionary *)arg4 completion:(void (^)(_Bool, NSError *))arg5;
- (void)beginMonitoringApplicationWithSpecifier:(XCUIApplicationSpecifier *)arg1;
@end

