name: CI-PR

on: pull_request

jobs:
  build:
    name: Test and build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 11.2
      run: sudo xcode-select -s /Applications/Xcode_11.2.app
    - name: Run Bluepill tests
      run: ./scripts/bluepill.sh test
    - name: Build Bluepill
      run: ./scripts/bluepill.sh build
